script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/zachlysobey/ui-router-playground.git
  - secure: "JgSEffrdt6pbE3c1LY9M4ESjoPhDO895oVSNr1pn2D73KK5C5pZTAfDM41f4SZ/sl4mIpP5ORLyQumNb+ZuolQxlh7MCJx4HFUksOvBvopFnwl3fc1tiACN3Ly2wstzHlEKMIGhgKI0lpBl236P1hRDnVFuo7Sc6+F4Muun4SzTnTEG4T3lOOdDE4kLHecs8VFXlkAB9oPV6Y23248YKpvaffeaYCYdtwG/VX6gJZX2bYMFpdCxJ1bxKCd0TnKUeAvKZobilmodeMR46eaOa+ewLEUIOYgU+WFwUN5XaYRZyb6jFyq6DcPSgzO8eZspYqx+1T2JnEssSGFpigYqdL/1N3LmY2sc3lwuxTXylAxLtJTkA2J8Zu8hq7n77xc1NIwo92Hu6QO3yO+Qk6IqtlP1ZOgktlP0hxTuUiX8IB1NOhQojSEj6n3oI1ciO8uyF9j6vps1iY40vJcWpIDd0rruyTJV1UeNhhS/j+qd7YjwZzI/fR87x/6l7TI+qcOlAUlA2jEg7bcg21TqJuMS+tTfN+ZgWnYesYudGA+Ih0JUs6ntOow5PNmvOZ1pcNgWscfTcPs11wU0QuixERpGRX3kMOyUVnYuWcK819xSMtjvDVGJwS7YbMBQw6r+gWISPInH+KJ4odIFGxw0Qq0tO8W/eMIrTH21IyxRZKXTw3P4="

